Created a file with common functions related to tag. (for #67 issue)
s-tip/stip-common pull request #68
Opened 2020-10-16 07:30 UTC by ta-hiroki

2020-10-16 08:20 UTC, uchimrina approved these changes
I checked it.

2020-10-18 23:46 UTC, stmtstk requested changes
@ta-hiroki 

Could you change the names of constant value to ALL UPPER CASE?

---

`re.compile` した値は定数なので、 `*_reg` という定数名は大文字に直してほしいです。

2020-10-19 00:00 UTC, stmtstk approved these changes

2020-10-19 00:00 UTC, stmtstk commented
@ta-hiroki @uchimrina 
Thanks for your cooperation.

2020-10-19 00:01 UTC, merged